version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.3
    - 2.4.5
  - dependency-name: org.testcontainers:junit-jupiter
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: org.testcontainers:testcontainers
    versions:
    - 1.15.1
    - 1.15.2
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.1
    - 1.15.2
